### ISSUE TITLE
how to add a point as (x,y) in R tree?

### ISSUE THREAD

**Issue by shuyaoyimei** [nushoin/RTree#13]
hello,nushoin
  i have read your code adn i have a question, you code insert a box when init the Rtree. could i add point as (x,y) in init Rtree and Rtree gennerted automatic ?
  Thanks!

**Comment by AlexVonB** [comment]
Hi, to add a single point instead of a rectangle, just add a rectangle with the second point equal to the first one:

```cpp
RTree<Foo*, double, 3> tree;
double min[3] = {1., 1., 1.};
double max[3] = {1., 1., 1.};
Foo* bar = new Foo();
tree.Insert(min, max, bar);
```

Best

**Comment by shuyaoyimei** [comment]
thanks for your answer, i want to add Latitude and longitude to the Rtree, and i dont know how to do it because of the data don't have  min and max,  the code like this.
ps:the data which i want to use [http://snap.stanford.edu/data/loc-gowalla.html](url)
`RTree<Foo*, double, 3> tree;`
`double point[3] = {1., 1., 1.};`
`Foo* bar = new Foo();`
`tree.Insert(point, bar);`
thanks for you response.

**Comment by AlexVonB** [comment]
That would work like this:

```cpp
RTree<int, double, 2> tree;
double point[2] = {lat, lon};
tree.Insert(point, point, location_id);
```

Best

**Comment by shuyaoyimei** [comment]
OK,i will try it.Thank you.
