### ISSUE TITLE
Question about rect segement intersections

### ISSUE THREAD

**Issue by twut** [nushoin/RTree#17]
Hi, 
I am a student who is studying R-Tree now.
I wonder if the tree.search() function also supports  Box-Segment intersection? So far the input is always a search_rectangle, could I directly input a segment represented by two 3D points, and get all the rectangles intersected with the input segment?

**Comment by AlexVonB** [comment]
Hi twut,
you could modify the Search function to not only return the points that were found, but also to collect or return the rectangles in the tree that overlap the search rectangle: https://github.com/nushoin/RTree/blob/master/RTree.h#L1616
Right now, the lib does not support your query directly. Feel free to open a pull request when you added this functionality.
Best, Alex

**Comment by twut** [comment]
Thanks!
