### ISSUE TITLE
doesn't compile in Visual Studio 2019 out of the box

### ISSUE THREAD

**Issue by yoavmil** [nushoin/RTree#19]
`fopen` gives some warning when compiling in MSVC compiler.

> C4996	'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details

easy workaround:
```c++
#pragma warning( push )
#pragma warning(disable:4996)
#pragma warning(disable:4244)
#include "RTree.h"
#pragma warning( pop )
```

also this line:
``` c++
ELEMTYPEREAL halfExtent = ((ELEMTYPEREAL)a_rect->m_max[index] - (ELEMTYPEREAL)a_rect->m_min[index]) * 0.5f;
```
gives this warning
> C4244	'initializing': conversion from 'float' to 'ELEMTYPEREAL', possible loss of data

it's probably the `* 0.5f`

But I must say, otherwise, this worked out of the box, in no time! and improved my code from O(n^2) to O(nlogn) and it's a blast.

**Comment by nushoin** [comment]
> `fopen` gives some warning when compiling in MSVC compiler.

The whole `RTFileStream` class is a hack. Anyway your quick and dirty solution seems fine.

> it's probably the `* 0.5f`

Makes sense, should probably add a cast, something like  `... * (ELEMTYPEREAL)0.5f;`

Would you care to open a PR? Also please make sure that you don't break *X builds - I think that the `#pragma` syntax is MSVC specific.

Last, TBH, I don't really maintain this project anymore. @AlexVonB - please forgive me if I stepped on your toes here...

**Comment by AlexVonB** [comment]
No worries @nushoin 😁 I am going to test the PR on Ubuntu as soon as it exists. Then I'll just merge it. Thanks for your insight! Greetings!

**Comment by yoavmil** [comment]
I can't make a pull request, because I don't have permissions. however:
```c++
  bool OpenRead(const char* a_fileName)
  {
#ifdef __STDC_WANT_SECURE_LIB__
     return (fopen_s(&m_file, a_fileName, "rb") == 0);
#else
     m_file = fopen(a_fileName, "rb");
     if (!m_file)
     {
         return false;
     }
     return true;
#endif
  }

  bool OpenWrite(const char* a_fileName)
  {
#ifdef __STDC_WANT_SECURE_LIB__
    return (fopen_s(&m_file, a_fileName, "wb") == 0);
#else
    m_file = fopen(a_fileName, "wb");
    if(!m_file)
    {
      return false;
    }
    return true;
#endif
  }
```
```c++
ELEMTYPEREAL halfExtent = ((ELEMTYPEREAL)a_rect->m_max[index] - (ELEMTYPEREAL)a_rect->m_min[index]) * (ELEMTYPEREAL)0.5;
```

**Comment by yoavmil** [comment]
BTW, what happens if `ELEMTYPEREAL` is `int`?

**Comment by AlexVonB** [comment]
Thank you! I'll make a new branch and include the changes. According to https://en.cppreference.com/w/c/io/fopen we should check for `__STDC_LIB_EXT1__` to be defined and `__STDC_WANT_LIB_EXT1__` to be `1`. Any reason why you checked for `__STDC_WANT_SECURE_LIB__` to be defined?

**Comment by AlexVonB** [comment]
Regarding the float-ness of `ELEMTYPEREAL`: According to https://github.com/nushoin/RTree/blob/master/RTree.h#L46 this should be either `float` or `double`, as the name `REAL` as in [real numbers](https://en.wikipedia.org/wiki/Real_number) suggests. We maybe should add this to the README.

**Comment by yoavmil** [comment]
I think there's a way to check it in compile time. I'll look for it.

**Comment by AlexVonB** [comment]
Great, thanks! https://en.cppreference.com/w/cpp/language/static_assert says that the message parameter in `static_assert` is C++17 or greater, so I would not include a message to maintain compatibility to at least C++11 (where `static_assert` was introduced and where RTree uses features like `std::function` of).

**Comment by yoavmil** [comment]
The other way around. message is 11, no message is 17

**Comment by AlexVonB** [comment]
Hi @yoavmil, do you have time to check if the branch [`fix-vsc-warnings`](https://github.com/nushoin/RTree/tree/fix-vsc-warnings) resolves all your issues? Thanks!

**Comment by yoavmil** [comment]
It doesn't compile because `__STDC_LIB_EXT1__` is not defined. I don't know why.

use this instead:
```c++
    bool Open(const char* a_fileName, const char* mode)
    {
#ifdef __STDC_WANT_SECURE_LIB__
        return fopen_s(&m_file, a_fileName, mode) == 0;
#else
        m_file = fopen(a_fileName, mode);
        return m_file != nullptr;
#endif
    }
```

or 
```c++
#if defined(_WIN32) && defined(__STDC_WANT_SECURE_LIB__)
        return fopen_s(&m_file, a_fileName, mode) == 0;
#else
        m_file = fopen(a_fileName, mode);
        return m_file != nullptr;
#endif
``` 
see [here](https://github.com/nothings/stb/issues/744)

**Comment by AlexVonB** [comment]
Thanks for checking. After installing Visual Studio 2019 myself and testing this, it seems that VS does not adhere to the standard they set... So I chose `defined(_WIN32) && defined(__STDC_WANT_SECURE_LIB__)` as fix, following the lead of [nothings/stb](https://github.com/nothings/stb/issues/744). Please quick-test it on you end, then I'll merge the branch. Best!

**Comment by yoavmil** [comment]
works. thanks
