### ISSUE TITLE
Rtree hierarch print

### ISSUE THREAD

**Issue by petrasvestartas** [nushoin/RTree#24]
Hi,

How can I print a list of all boxes in an rtree to vizualize the tree hierarchy like the image below (blue boxes)?

![image](https://user-images.githubusercontent.com/18013985/148661994-5bceb0dc-89dc-4594-bfd0-f26d83d24a8e.png)

My current code for neighbour search is this:

```
	//////////////////////////////////////////////////////////////////////////////
	// Create RTree
	//////////////////////////////////////////////////////////////////////////////

	RTree<int, double, 3> tree;

	//////////////////////////////////////////////////////////////////////////////
	// Insert AABB
	//////////////////////////////////////////////////////////////////////////////

	for (int i = 0; i < elements.size(); i++) {
		double min[3] = { elements[i].aabb.xmin(), elements[i].aabb.ymin(), elements[i].aabb.zmin() };
		double max[3] = { elements[i].aabb.xmax(), elements[i].aabb.ymax(), elements[i].aabb.zmax() };
		tree.Insert(min, max, i);
	}

	//////////////////////////////////////////////////////////////////////////////
	// Search Closest Boxes | Skip duplicates pairs | Perform callback with OBB
	//////////////////////////////////////////////////////////////////////////////
	std::vector<int> result;
	for (int i = 0; i < elements.size(); i++) {//AABB.size()

		//std::vector<int> result;
		auto callback = [&result, i, &elements](int foundValue) -> bool
		{

			if (i < foundValue && cgal_box_util::GetCollision(elements[i].oob, elements[foundValue].oob)) {
				result.push_back(i);
				result.push_back(foundValue);
			}
			return true;
		};

		double min[3] = { elements[i].aabb.xmin(), elements[i].aabb.ymin(), elements[i].aabb.zmin() };
		double max[3] = { elements[i].aabb.xmax(), elements[i].aabb.ymax(), elements[i].aabb.zmax() };
		int nhits = tree.Search(min, max, callback);//callback in this method call callback above

	}
```

**Comment by AlexVonB** [comment]
Hi! There is an iterator that allows you to list all AABBs in the tree. For an example usage see
https://github.com/nushoin/RTree/blob/b9a71b04f7717763b08664d24ee0f4722d11f68e/Test.cpp#L97-L109
or
https://github.com/nushoin/RTree/blob/b9a71b04f7717763b08664d24ee0f4722d11f68e/Test.cpp#L111-L119
where `copy` is the tree (named `copy` here because we test the copy-constructor).
Let me know if that resolved your question! Best

**Comment by petrasvestartas** [comment]
Hi,

This prints objects inside the rtree:
![image](https://user-images.githubusercontent.com/18013985/148684918-79d90092-6435-4504-a9c7-e93d430ba461.png)


I am searching for how to print the hierarchy itself.
Do you know how to do it?

**Comment by AlexVonB** [comment]
I see, this would be what `Search` does internally:

https://github.com/nushoin/RTree/blob/dfc7f706b1fd1e8a9d7a3888581b15d8c8e7c32d/RTree.h#L1605-L1644

Unfortunately, the functions and fields are `protected`, so you are not able to use them. You could set them public here:

https://github.com/nushoin/RTree/blob/dfc7f706b1fd1e8a9d7a3888581b15d8c8e7c32d/RTree.h#L278

or (preferably) create a new public function that returns the tree. If you do so, please consider creating a merge request :)

**Comment by petrasvestartas** [comment]
Thank you I changed to public.
But I am afraid that this is to complicated to understand for me how to print the list of boxes as nodes.

Is there any possibility you could show an example?

**Comment by AlexVonB** [comment]
Hi! I implemented `RTree::ListTree` for you: https://github.com/nushoin/RTree#iterating Best, Alex

**Comment by petrasvestartas** [comment]
Woohoo, I'll try it out

**Comment by petrasvestartas** [comment]
works nicely, I am using your rtree search for timber joint detection.
https://github.com/ibois-epfl/compas_wood

Thank you

![rtree_hierarchy](https://user-images.githubusercontent.com/18013985/148698792-5d8d92d7-1db4-451b-874b-fb9f66ba8b0b.gif)

**Comment by AlexVonB** [comment]
Really nice of you to post an update, thanks! Glad I could help! :)
